
Kalamu\CmsAdminBundle\Entity\ContextPublication:
    type: entity
    table: kalamu_context_publication
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            unique: true
            length: 255
        title:
            type: text