
Kalamu\CmsAdminBundle\Entity\Post:
    type: entity
    table: kalamu_post
    gedmo:
        loggable: true
    lifecycleCallbacks:
        prePersist: [updatePublishTimestamp]
        preUpdate: [updatePublishTimestamp]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        title:
            type: text
            gedmo:
                - versioned
        slug:
            type: string
            length: 255
            gedmo:
                versioned: ~
                slug:
                    separator: -
                    style: default
                    updatable: false
                    unique: true
                    fields:
                        - title
            unique: true
        resume:
            type: text
            nullable: true
            gedmo:
                versioned: ~
        contenu:
            type: text
            nullable: true
            gedmo:
                versioned: ~
        image:
            type: text
            nullable: true
            gedmo:
                versioned: ~
        template:
            type: text
            nullable: true
            gedmo:
                versioned: ~

        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        created_by:
            type: string
            gedmo:
                blameable:
                    on: create
        updated_by:
            type: string
            gedmo:
                blameable:
                    on: update
        published_at:
            type: datetime
            nullable: true
        published_until:
            type: datetime
            nullable: true
        metas:
            type: json_array
            nullable: true
            gedmo:
                versioned: ~

    manyToOne:
        publish_status:
            targetEntity: Kalamu\CmsAdminBundle\Entity\PublishStatus
            joinColumn:
                name: ref_status
                referencedColumnName: id


    manyToMany:
        terms:
            targetEntity: Kalamu\CmsAdminBundle\Entity\Term
            joinTable:
                name: post_aff_term
                joinColumn:
                    ref_post:
                        referencedColumnName: id
                        onDelete: CASCADE
                inversedJoinColumn:
                    ref_term:
                        referencedColumnName: id
                        onDelete: CASCADE

        context_publication:
            targetEntity: Kalamu\CmsAdminBundle\Entity\ContextPublication
            joinTable:
                name: kalamu_post_context
                joinColumns:
                    ref_post:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    ref_context:
                        referencedColumnName: id
                        onDelete: CASCADE