
KalamuCmsAdminBundle_elfinder:
    resource: "@KalamuCmsAdminBundle/Resources/config/routing/elfinder.yml"
    prefix:   /elfinder

KalamuCmsAdminBundle_link_picker_api:
    resource: "@KalamuCmsAdminBundle/Resources/config/routing/api_link_picker.yml"
    prefix:   /api/link_picker


KalamuCmsAdminBundle_menu:
    resource: "@KalamuCmsAdminBundle/Resources/config/routing/menu.yml"
    prefix:   /menu