
services:

    kalamu_cms.admin_extension.contextualizable:
        class: Kalamu\CmsAdminBundle\Admin\Extension\ContextualizableExtension
        arguments: ['@kalamu_cms_core.content_type.manager']
