
services:

    kalamu_cms.form_type.publish_status_interfaces:
        class: Kalamu\CmsAdminBundle\Form\Type\PublishStatusInterfacesType
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: publish_status_interfaces }

    kalamu_cms.form_type.classifiable:
        class: Kalamu\CmsAdminBundle\Form\Type\ClassifiableType
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: classifiable }
