
services:

    ## Menu provider for knp
    kalamu_cms_admin.menu_provider:
        class: Kalamu\CmsAdminBundle\Menu\MenuProvider
        arguments: ['%kalamu_cms_core.menus%', '@knp_menu.factory', '@doctrine']
        tags:
            - { name: knp_menu.provider }

    # Abstract service for ItemPicker
    kalamu_cms_admin.item_picker.base_manager:
        abstract: true
        class: Kalamu\CmsAdminBundle\Menu\DefaultMenuItemPicker

    # Manager for itemPickers
    kalamu_cms_admin.menu_item.manager:
        class: Kalamu\CmsAdminBundle\Manager\MenuItemPickerManager

    # dynamique MenuItemPicker for taxonomies
    kalamu_cms_admin.menu_item.taxonomie_picker:
        class: Kalamu\CmsAdminBundle\Menu\TaxonomieMenuItemProvider
        arguments: ['@doctrine', '@knp_paginator', '@kalamu_cms_core.content_type.manager']
        tags:
            - { name: kalamu_cms_admin.menu_item_picker.provider }

    kalamu_cms_admin.menu_item.index_picker:
        class: Kalamu\CmsAdminBundle\Menu\IndexMenuItemPicker
        arguments: ['@doctrine', '@knp_paginator', '@kalamu_cms_core.content_type.manager', '@router']
        tags:
            - { name: kalamu_cms_admin.menu_item_picker, alias: index, label: Index Pages }