parameters:

    # Templates des widgets
    kalamu_cms.element.cms.last_content.template: KalamuCmsAdminBundle:Widget:last_content.html.twig
    kalamu_cms.element.cms.form_contact.template: KalamuCmsAdminBundle:Widget:form_contact.html.twig

    kalamu_cms.element.cms.card_link.template: KalamuCmsAdminBundle:Widget/CMS:card_link.html.twig
    kalamu_cms.element.cms.accordion.templates:
        accordion:
            title: 'Accordéon déroulant'
            template: 'KalamuCmsAdminBundle:Widget/CMS:accordion.html.twig'
        blocks:
            title: 'Blocks'
            template: 'KalamuCmsAdminBundle:Widget/CMS:blocks.html.twig'
    kalamu_cms.element.cms.isotope_cards.template: KalamuCmsAdminBundle:Widget/CMS:isotope_cards.html.twig

services:

    # Widgets
    kalamu_cms.element.cms.last_content:
        class: Kalamu\CmsAdminBundle\Widget\LastContentWidget
        arguments: ['@kalamu_cms_core.content_type.manager', %kalamu_cms.element.cms.last_content.template%]
        tags:
            - { name: dashboard.widget }

    kalamu_cms.element.cms.form_contact:
        class: Kalamu\CmsAdminBundle\Widget\FormContactWidget
        arguments: ['@form.factory', %kalamu_cms.element.cms.form_contact.template%, '@mailer', '@event_dispatcher']
        calls:
            - [setRequestStack, ['@request_stack']]
        tags:
            - { name: dashboard.widget }

    kalamu_cms.element.cms.accordion:
        class: Kalamu\CmsAdminBundle\Widget\CMS\AccordionWidget
        arguments: [%kalamu_cms.element.cms.accordion.templates%]
        tags:
            - { name: dashboard.widget }

    kalamu_cms.element.cms.card_link:
        class: Kalamu\CmsAdminBundle\Widget\CMS\CardLinkWidget
        arguments: [%kalamu_cms.element.cms.card_link.template%]
        tags:
            - { name: dashboard.widget }
