
api_link_picker:
    path:     /
    defaults: { _controller: "KalamuCmsAdminBundle:API/LinkPicker:index" }

api_link_picker_base:
    path:     /base
    defaults: { _controller: "KalamuCmsAdminBundle:API/LinkPicker:base" }
